collections_config:
  data:
    path: src/config
    name: Data
    icon: roofing
  authors-en:
    path: src/content/authors/english
    url: '/en/authors/[slug]/'
    name: Authors 
    icon: person
  authors-fr:
    path: src/content/authors/french
    url: '/fr/authors/[slug]/'
    name: Authors (Fr)
    icon: person
  blog-en:
    path: src/content/blog/english
    url: '/en/blog/[slug]/'
    name: Blog 
    icon: newspaper
  blog-fr:
    path: src/content/blog/french
    url: '/fr/blog/[slug]/'
    name: Blog (Fr)
    icon: newspaper
  pages-en:
    path: src/content/pages/english
    url: '/en/[slug]/'
    name: Pages
    icon: cottage
  pages-fr:
    path: src/content/pages/french
    url: '/fr/[slug]/'
    name: Pages (Fr)
    icon: cottage
  sections-en:
    path: src/content/sections/english
    name: Sections
    _enabled_editors:
      - data
    icon: content_paste_search
  sections-fr:
    path: src/content/sections/french
    name: Sections (Fr)
    _enabled_editors:
      - data
    icon: content_paste_search
  translations:
    path: src/i18n
    name: Src I18n
    icon: archive
paths:
  static: public
  uploads: public/images
timezone: Pacific/Auckland
markdown:
  engine: commonmark
  options:
    gfm: true
    linkify: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    breaks: false
    xhtml: false
    attributes: false
    typographer: false
    treat_indentation_as_code: true
