collections_config:
  data:
    path: src/config
    name: Data
    icon: roofing
  authors:
    path: src/content/authors
    name: Authors 
    icon: person
  blog:
    path: src/content/blog
    name: Blog 
    icon: newspaper
  pages:
    path: src/content/pages
    url: '[full_slug]'
    name: Pages
    icon: cottage
  sections:
    path: src/content/sections
    name: Sections
    icon: content_paste_search
  translations:
    path: src/i18n
    name: Src I18n
    icon: archive
paths:
  static: public
  uploads: public/images
timezone: Pacific/Auckland
markdown:
  engine: commonmark
  options:
    gfm: true
    linkify: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    breaks: false
    xhtml: false
    attributes: false
    typographer: false
    treat_indentation_as_code: true
